quest-academia/laravel-posts-training

- app/Http/Controllers/PostsController.php
- app/Post.php
- database/migrations/2021_02_26_005338_create_posts_table.php
- database/seeds/DatabaseSeeder.php
- database/seeds/PostsTableSeeder.php
- resources/views/layouts/app.blade.php
- resources/views/posts/posts.blade.php
- resources/views/welcome.blade.php
- routes/web.php
ズームでのお話を参考にしながら、自分で調べつつ、自分が思うようにやってみました。
ご確認のほど、よろしくお願いします。
> add:PostsTableのマイグレーションとシーダーの追加

- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/PostsController.php
- resources/views/posts/create.blade.php
- resources/views/posts/edit.blade.php
- resources/views/posts/index.blade.php
- resources/views/posts/show.blade.php
- routes/web.php
個人課題の新規投稿画面が完了しました。
よろしくお願い致します。
> 個人課題：新規投稿画面の完了(nao)

- app/Http/Controllers/PostsController.php
- composer.json
- composer.lock
- public/css/commons.css
- resources/views/commons/footer.blade.php
- resources/views/commons/header.blade.php
- resources/views/layouts/app.blade.php
- resources/views/posts/show.blade.php
- resources/views/welcome.blade.php
- routes/web.php
投稿詳細画面を作成いたしましたのでご確認よろしくお願いします！
> 3.投稿詳細画面作成しました

- app/Providers/2021_03_09_AppServiceProvider.php
- database/migrations/2021_03_15_125512_create_posts_table.php
- database/seeds/DatabaseSeeder.php
- database/seeds/PostsTableSeeder.php
- resources/views/welcome.blade.php
月曜日のミーティングの際に教えてくださりありがとうございました。
間違えてdevelop_otaniの方で作業してしまい、そのままプッシュをしてしまいました。
developはmasterなので作業禁止を念頭に置き次回から同じことが起きないように注意して行いなす。
すみませんでした。
> マイグレーションとシーダー

- app/Http/Controllers/PostsController.php
- resources/views/layouts/app.blade.php
- resources/views/posts/show.blade.php
- routes/web.php
**やった事**
　• 削除のルーティングとコントローラの実装
　• 編集ボタンと削除ボタンの位置設定
**編集箇所**
　• PostsController
　• web.php
　• show.blade.php
　• app.blade.php
ーーーーーーーーーーーーーーーーーーーーーーーーー
**訂正**
　• PostsController　→　改行
　• app.blade.php　→　cssの記述を削除
ご確認よろしくお願い致します。
> 投稿削除の実装（nao）

- app/Http/Controllers/PostsController.php
- resources/views/posts/index.blade.php
- resources/views/posts/show.blade.php
- routes/web.php
PostsController.php,index.blade.php,web.phpの編集（修正と書きましたが、編集です。すみません。）show.blede.phpの追加を行いました。
syntax error, unexpected 'Y' (T_STRING),というエラー文が表示され、エラーとして赤くなっているところが「投稿日時:<?php echo e($post->created_at->format('Y.m.d')); 」のところで、なぜそこにエラー表示されるのか、自分でエラー文の意味など調べるなどしましたが、わかりません。
そこで一度ご確認していただきたく、プルリクを行いました。
ご確認、ご指摘のほど、よろしくお願いします。
> PostsController.php,index.blade.php,web.phpの修正,show.blede.phpの追加

- app/Http/Controllers/UsersController.php
- resources/views/users/edit.blade.php
- resources/views/users/show.blade.php
- routes/web.php
ユーザ更新画面の作成が終わりました。
時間がかかってしまい申し訳ありません。
ご確認よろしくお願いいたします。
解決しました。
> （共同開発）ユーザ更新画面

- app/Http/Controllers/CommentsController.php
- app/Http/Requests/CommentRequest.php
- resources/views/comments/comment_error_card.blade.php
- resources/views/comments/comments.blade.php
- resources/views/commons/header.blade.php
- resources/views/layouts/app.blade.php
- resources/views/users/show.blade.php
- resources/views/welcome.blade.php
- routes/web.php
コメント投稿機能の現在の編集分です。
CommentsControllerにcomment関数を作成しました。
その下のstoreは奈緒さんがコメント表示の際に作成したものらしいのですが念のため残してあります。
comments.blade.php内に投稿フォームを作成しました。
先日の写真のままにしてあります。
ご確認よろしくお願いします。
> 共同開発：コメント投稿機能1

- resources/views/commons/footer.blade.php
- resources/views/commons/header.blade.php
header,footer.blade.phpの作成を行いました。
ご確認のほどよろしく願いします。
> header,footer.blade.phpの作成

- app/Http/Controllers/PostsController.php
- app/Post.php
- resources/views/index.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
投稿一覧画面を作成いたしました。
そうやさんが作ったヘッターフッターをマージしてくるために一度コミットしてあります。
ログインをしていなくても見れるようにしています。
ご確認よろしくお願いいたします。
> (共同開発)投稿一覧画面

- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- routes/web.php
login.blade.php作成、register.blade.php,web.phpの編集し、ユーザーログイン画面を作成しました。
ご確認のほどよろしくお願いします。
> login.blade.php作成、register.blade.php,web.phpの編集

- app/Http/Controllers/PostsController.php
- resources/views/create/edit.blade.php
- resources/views/index.blade.php
- routes/web.php
投稿編集画面を作成しました。
ログインしていなくても編集できるようにしてあります。
次回の削除機能の時に、コメントアウトして完成版にします。
ご確認よろしくお願いいたします。
> (共同開発)投稿編集画面作成

- app/Http/Controllers/PostsController.php
- resources/views/index.blade.php
- routes/web.php
投稿削除機能を実装しました。
・web.php
・index.blade.php
・PostsController.php
web.phpでのdeleteのルーティングを書く際に、
https://qiita.com/kuroudoart/items/44eca2150f102ba7fdb4
https://nodoame.net/archives/11628
の２つのサイトを参考にして作成したのですが、この書き方でいいのでしょうか？
そうやさんのプッシュしているのがコンフリクトしているので、そうやさんのが先にマージされた場合に自分のもコンフリクトをおこすとおもうのですが、プッシュさせていただきました。
> （共同開発）投稿削除機能

- app/Http/Controllers/UsersController.php
- resources/views/users/show.blade.php
- routes/web.php
UsersController.php,show.blade.,e.php,web.phpの編集
git push -f origin ブランチ名で強制的にPushを行いました。
> UsersController.php,show.blade.,e.php,web.phpの編集

- app/Http/Controllers/PostsController.php
- database/migrations/2021_04_20_210632_create_posts_table.php
- resources/views/index.blade.php
編集した箇所
・2021_04_20_210632_create_posts_table.php
・index.blade.php
・PostsController.php
投稿編集をして更新をした際にうまく更新できていなかったので、編集しました。
「編集」「削除」ボタンをログインしていなければ表示されないようにしました。
投稿一覧画面のアイコンからユーザ詳細画面に飛ぶようにしました。
ご確認よろしくお願いいたします。
> （共同開発）投稿編集画面修正

- resources/views/welcome.blade.php
> welcome.bladeを更新

- database/migrations/2021_05_05_013629_create_posts_table.php
- database/seeds/DatabaseSeeder.php
- database/seeds/PostsTableSeeder.php
■やったこと
・php artisan migrate マイグレーション実行
・php artisan make:seed PostsTableSeeder シーダー作成
■考慮して欲しいこと
・DaichiさんのgitHubの名前がわからなかったのでReviewersに追加していないです。
ご確認のほどよろしくお願いします。
> postsマイグレーションとシーダー作成　#71

- app/Http/Middleware/RedirectIfAuthenticated.php
- routes/web.php
お疲れ様です。
やったこと
- ログインしていない場合でTopページにアクセスした場合はログイン画面にリダイレクトするように修正。
ご確認のほどお願いします。
> ログインしていない場合はログイン画面にリダイレクトするように修正。

- app/Http/Controllers/PostsController.php
- resources/views/common/header.blade.php
- resources/views/layouts/app.blade.php
- resources/views/post/create.blade.php
- routes/web.php
■やったこと
・PostsControllerにcreate,storeメソッド追加
・登録画面、登録保存処理のルーティング追加
・ヘーダー（投稿する,ホームアイコン）にリンク追加
・登録画面作成
登録動作確認済です。
コードレビューよろしくお願いします。
> 新投稿登録機能作成 #81

- resources/views/auth/login.blade.php
- routes/web.php
お疲れ様です。  
ユーザーログイン画面の実装ができましたので、ご確認の程よろしくお願いいたします。
やったこと  
•login.blade.phpの作成、中身の記述  
編集したところ  
•web.phpに以下を追加
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login')->name('login.post');
Route::get('logout','Auth\LogoutController@logout')->name('logout');
こちらの記載方法で問題ないでしょうか。  
お忙しいところ恐れ入りますが、ご確認のほど、どうぞよろしくお願いいたします。
> add:ログイン機能の実装　＃９２

- app/Http/Controllers/PostsController.php
- resources/views/post/edit.blade.php
- resources/views/post/index.blade.php
- routes/web.php
やったこと
・編集と更新 ルーティング&メソッド追加
・投稿一覧画面に編集機能追加（ログインしているユーザーと投稿したユーザーが一致した場合編集が可能）
・編集画面作成
確認のほどよろしくお願いします。
> 編集&更新機能作成 #82

- app/Http/Controllers/PostsController.php
- resources/views/post/index.blade.php
- routes/web.php
■やったこと
・削除　ルーティング、コントローラ（メソッド） 作成
・削除画面作成　（削除するときにポップアップ が表示されるようにしています）
確認のほどよろしくお願いします。
> 削除機能作成 #80

- app/Http/Controllers/CommentsController.php
- resources/views/post/comment.blade.php
- resources/views/post/commentEdit.blade.php
- resources/views/post/edit.blade.php
- routes/web.php
■やったこと
・編集,更新　ルーティングとコントローラ（メソッド）追加
・編集画面作成
・ログインしているユーザーとコメントしたユーザーが一致している場合のみ、コメントが編集できるように設定。
確認のほどよろしくお願いします。
> コメント編集&更新 #151

- resources/lang/ja/auth.php
- resources/lang/ja/pagination.php
- resources/lang/ja/passwords.php
- resources/lang/ja/validation.php
お疲れ様です！
バリデーションの日本語化で消えていた日本語化ファイルを追加しました。
どうぞご確認のほどよろしくお願いいたします。
> add:日本語化バリデーションの追加 #117

- app/Http/Controllers/CommentsController.php
- resources/views/post/comment.blade.php
- resources/views/post/index.blade.php
- routes/web.php
お疲れ様です！
やったこと
- コメント削除アクションを実装。
- コメント削除アクションへのルーティングを追加。
- 投稿一覧に削除ボタンを追加。
- 成功、失敗メッセージを表示。
確認のほど、よろしくお願いします。
> コメント削除機能を実装。 #150

- app/Http/Controllers/CommentsController.php
- app/Http/Controllers/PostsController.php
- resources/views/layouts/app.blade.php
- resources/views/post/commentEdit.blade.php
- resources/views/post/create.blade.php
- resources/views/post/edit.blade.php
■やったこと
・各ページにバリデーションエラーメッセージファイル追加。
・投稿,コメントの編集、更新、削除に「他のユーザーが変更できないようする」ソースを記載。
確認のほどよろしくお願いします。
> バリデーションエラーメッセージファイル変更＆編集、更新、削除に「他のユーザーが変更できないようする」

- app/Http/Controllers/PostsController.php
- resources/views/posts/index.blade.php
- routes/web.php
「B: 投稿削除機能 #80」が見当たりませんでしたので、Aのでプルリクします。
やったこと
PostsController.php
web.php
の編集。以上、よろしくお願いいたします。
> 投稿削除機能 #80

- app/Comment.php
- app/Http/Controllers/CommentsController.php
- database/seeds/DatabaseSeeder.php
- resources/views/posts/index.blade.php
やったこと
• コメント表示アクションを実装。
• コメントコントローラーを追加。
• コメントを表示。
確認のほど、よろしくお願いします。
> B : 投稿一覧のコメントの部分（表示のみ） #98

- app/Http/Controllers/UsersController.php
- app/Http/Requests/UserRequest.php
- resources/views/auth/login.blade.php
- resources/views/commons/header.blade.php
- resources/views/commons/renew.blade.php
- resources/views/users/edit.blade.php
- resources/views/users/show.blade.php
- routes/web.php
お疲れ様です！
ユーザー更新機能の実装が完了しましたので、ご確認のほどよろしくお願い致します。
やったこと
• UsersControllerに更新画面、更新処理メソッドを追加。
• ユーザー更新画面の実装
• 詳細画面から更新画面へのリンクを設定
• 更新画面と更新処理へのルーティングを追加。
•ヘッダーにログインしている時はユーザー詳細画面、していない場合ログイン画面へのリンク設定。
考慮して欲しいこと
先日ご教示頂きました以下の箇所のご確認をいただけると幸いです。
①header.balde.php での<ul>内のインテンドを揃える。
②ログインしてい以外のユーザー編集ページにURLからアクセスしてにloginに戻るように設定。
③ユーザー情報を更新する際に、IDが同じ場合はメールアドレスの重複チェックを除外するよう設定。
④ユーザー編集の際、パスワードにHash設定。
お忙しいところ恐れ入りますが、どうぞよろしくお願い致します🙇‍♂️
> ユーザ更新画面の実装　#93

- app/Comment.php
- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/CommentsController.php
- app/Http/Controllers/PostsController.php
- app/Http/Requests/CommentRequest.php
- database/migrations/2021_05_13_053053_create_comments_table.php
- resources/views/posts/index.blade.php
- routes/web.php
@hsg0830 @Akrjourney 
お疲れ様です。
コメント投稿機能につきまして
やったこと
•コメント投稿のルーティングを追加。
• コメント投稿コントローラー設定。
• コメント投稿バリデーションファイル作成。
• コメント投稿フォームをまさきさんの`index.balde.php`に追加。
考慮して欲しいこと
`index.blade.php`内のドット記法や`CommentRequest`内のバリデーションのアスタリスクに関しましてはコウさんにご教示いただき実装した部分になりますが、まだ挙動など完全に理解していない部分などもございますので、引き続き復習して行きたいと思います。
>   コメント投稿機能実装　#97

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/PostsController.php
- app/Post.php
- app/User.php
- database/migrations/2021_06_09_205043_create_posts_table.php
- database/seeds/PostsTableSeeder.php
- database/seeds/UsersTableSeeder.php
- resources/views/posts/index.blade.php
- routes/web.php
やったこと
web.phpのトップページをPostscontrollerのindexアクションに指定し、
foreachを使い各ユーザーごとにtitleとbodyを取り出しました。
編集したこと
・web.phpでPostsControllerのindexアクションに指定。
・PostsControllerで投稿を＄postsとして全て取得。
・posts.index.phpで受け取った$postsから各ユーザーごとに
titleカラムとbodyカラムを表示できるようにしました。
> 投稿一覧画面作成 #167

- app/Http/Controllers/PostsController.php
- resources/views/posts/index.blade.php
- routes/web.php
・やったこと
投稿削除機能を実装しました。
・編集箇所
web.phpでrouteを指定
PostsControllerのdestroyメソッドの実装
posts.index.phpの削除ボタンにroute投稿のidを指定しました。
・考慮して欲しいこと
コントローラーのdeleteメソッドが呼び出せていないので
引数の間違いかroute指定の間違いかと考えています。
おかしい箇所が検討つかずの状態なので
一度確認していただけませんか。よろしくお願いします。
> 投稿削除機能の作成 #172

- app/Comment.php
- app/Http/Controllers/CommentsController.php
- app/Http/Requests/CommentRequest.php
- app/Post.php
- app/User.php
- config/database.php
- database/migrations/2021_06_19_011639_create_comments_table.php
- resources/views/comments/comment.blade.php
- resources/views/posts/edit.blade.php
- resources/views/posts/index.blade.php
- routes/web.php
・何をしたか　
コメント機能の作成をしました。
・編集箇所
Routeのstoreアクション
Commentモデルの追加と編集
PostモデルとCommentモデルの紐付け
Commentコントローラーのstoreアクションの実装
index.bladeのコメント部分の実装
・考慮して欲しいこと
Routeは後ほどbladeに記載する形で良いかどうか伺いたいです。
レビューよろしくお願いします。
> #171 コメント投稿機能の作成

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/UsersController.php
- resources/views/commons/header.blade.php
- resources/views/layouts/app.blade.php
- resources/views/users/details.blade.php
編集したこと(Why)
・ユーザー詳細画面（users.details.blade.php）の作成
・ユーザー詳細画面（users.details.blade.php）のログアウト処理記述
・UsersControllerのshowアクションを記述
・LoginControllerのlogoutメソッドをオーバーライド
バリデーションの有無
無
レビュワーに考慮してほしいこと
前回同様、考慮不足があればご指摘ください。
> #165ユーザー詳細画面の作成　須賀

- resources/views/commons/footer.blade.php
- resources/views/commons/header.blade.php
ヘッダーとフッターの作成（モックアップ参照）
viewsフォルダの下にcommonsフォルダを作成しその中にファイルを作成(header.blade.php,footer.blade.php)
再現できていかの確認
特になし
> ヘッダーフッターのbladeファイル作成(ひかる)

- app/Http/Controllers/PostsController.php
- app/Post.php
- app/User.php
- resources/views/posts/index.blade.php
- routes/web.php
- web.phpにルーティングの追加
- Modelファイル(Post.php)にリレーションを追加
- PostsControllerを作成し、index関数を作成
- index.blade.phpを作成
- 192.168.33.11を開き、index.blade.phpが表示され、postデータも全て表示されていることを確認しました。
> 投稿一覧画面の作成(美音)

- app/Http/Controllers/Auth/LoginController.php
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- routes/web.php
実装内容(What)
ログイン機能の実装
ログイン画面の作成
レビュワーに考慮してほしいこと
コードのレビューをお願いします。
補足
特になし
> ログイン画面の作成（綾花）

- app/Http/Controllers/UsersController.php
- resources/views/commons/header.blade.php
- resources/views/posts/index.blade.php
- resources/views/users/show.blade.php
- routes/web.php
実装内容(What)
ユーザー詳細画面を作成
テスト証跡
自分自身の詳細画面と他ユーザーの詳細画面両方とも確認済み
ヘッターから詳細画面へ飛べるかも確認済み
レビュワーに考慮してほしいこと
コード、デザインの確認をお願い致します。
補足
特になし
> ユーザー詳細画面を作成
